//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : openglGame
//  @ File Name : NPC.h
//  @ Date : 14/03/2017
//  @ Author : 
//
//


#if !defined(_NPC_H)
#define _NPC_H

#include "Entity.h"

class NPC : public Entity {
private:
	bool isAlly;
public:
	NPC();
};

#endif  //_NPC_H
