//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : openglGame
//  @ File Name : Player.h
//  @ Date : 14/03/2017
//  @ Author : 
//
//


#if !defined(_PLAYER_H)
#define _PLAYER_H

#include "Entity.h"

class Player : public Entity {
private:

public:
	Player();
	void moveRight();
	void moveLeft();
};

#endif  //_PLAYER_H
