//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : openglGame
//  @ File Name : Prop.h
//  @ Date : 14/03/2017
//  @ Author : 
//
//


#if !defined(_PROP_H)
#define _PROP_H

#include "Entity.h"

class Prop : public Entity {
public:
	Prop();
};

#endif  //_PROP_H
