//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : openglGame
//  @ File Name : Scene.h
//  @ Date : 14/03/2017
//  @ Author : 
//
//


#if !defined(_SCENE_H)
#define _SCENE_H


class Scene {
public:
	Scene();
};

#endif  //_SCENE_H
