//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : openglGame
//  @ File Name : Texture.h
//  @ Date : 14/03/2017
//  @ Author : 
//
//


#if !defined(_TEXTURE_H)
#define _TEXTURE_H


class Texture {
public:
	Texture();
};

#endif  //_TEXTURE_H
